language: rust
sudo: false

env:
  global:
    - secure: M2Ych+2OGwVW1605lNlzP0cDguLsf55NGvnQxgdQOGFHoVA5FWG3nA36UYz85AGoUoAxiVVXIZpyWxPaRd1GrCU0QixTYBFNELvb1Cr4sizcEpPtsHksjxOhOZ5EzA7/6V6FJ0///Bu2+VW+FSaen0eRHyfoFErJBanu8TCvpqY=

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
  - ./check-line-length.sh

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash upload-docs.sh'

branches:
  only: master

notifications:
  email:
    on_success: never
