language: rust

env:
  global:
    - secure: BE+ADwEi92STkK/cjPxDvs2orMkuP5152uaDRST4ZD3Y73n4KTlyq0HXu1YwGLPufo8a4xj6lRoOtLbEL1DSjbQEVN7dlxQiFq1rjZM4nPlNvvTSUJHz9awT52oILPoTirsZfYpqpW9lQ6gHSpa/Eagrmk7haMo1J7O3vcehvjM=

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
  - ./check-line-length.sh

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash upload-docs.sh'

branches:
  only: master
